"""morpho_crossbar — the matmul as a crossbar, in MorphoHDL.

The wkv/S6 work described a language model's *recurrence*, which the atlas
page measured at 0.2% of the model's arithmetic. This describes the other
99.8%: the projections, as a crossbar.

A crossbar is a grid where every crosspoint holds a weight, inputs travel
along rows, and products accumulate down columns. Memristive arrays do this
in the analog domain: Ohm's law multiplies, Kirchhoff's current law sums.

Deng et al. (Nature Communications 2026) go further than a multiply, and the
distinction matters. Wrapping the array in op-amp feedback makes the
circuit's *settling point* the solution to a linear system —
V_o = -A^T(AA^T)^-1 V_y — so a matrix pseudo-inverse falls out in one step,
in about 128 ns, with no iteration at all. A digital crossbar cannot do
that. Multiplication maps across; inversion does not, because digitally an
inverse is an iterative solve and there is no equivalent of letting physics
find a fixed point.

So this file claims the narrower thing: the same *topology*, in exact
digital logic, for the multiply-accumulate half. Gates per crosspoint
instead of one device — and in exchange, no converters, no conductance
drift, no write-and-verify, and no 1.83-5.61 dB gap to the numerical model.

Both are built here so the comparison is concrete rather than rhetorical:

    crosspoint(w, x)      one multiply — the cell at a grid intersection
    column(w_row, x)      products accumulated down one column: a dot product
    crossbar(...)         columns generated by recursion: the matrix-vector
                          product, at any size, from one definition

    python morpho_crossbar.py
"""

import numpy as np

from tiny_morpho import (
    morpho, compile, LSLICE, CAT, ZERO, VOID, brent_kung_adder,
)
from morpho_lm import qmul_s, bits_of, ints_of, sref


# ---------------------------------------------------------------- the cell

@morpho
def crosspoint(w, x):
    """One intersection: a stored weight times the value passing through it.

    In a memristive array this is a single device, and the multiply is
    physics. Here it is a Wallace tree — exact, and about 295 gates at 8
    bits, which is the price of not needing a converter.
    """
    return qmul_s(w, x, len(w) // 2)


def _column_done(w_ref, w_row, x):
    return VOID


@morpho(fallback=_column_done)
def column(w_ref, w_row, x):
    """One output: every crosspoint in a column, summed.

    The analog array sums by wiring the column to a single node and letting
    the currents add. Digitally the sum is an adder tree, which is where the
    depth comes from — but it is exact, and it is the same shape.
    """
    w0, wr = LSLICE(w_row, w_ref)
    x0, xr = LSLICE(x, w_ref)
    prod = crosspoint(w0, x0)
    rest = column(w_ref, wr, xr)
    if len(rest) == 0:
        return prod
    total, _c = brent_kung_adder(prod, rest, ZERO)
    return total


def _bar_done(w_ref, row_ref, W, x):
    return VOID


@morpho(fallback=_bar_done)
def crossbar(w_ref, row_ref, W, x):
    """The whole array: rows peeled off W, each one a column of the crossbar.

    `w_ref` sets the element width, `row_ref` the row width — the two
    reference buses that let one definition serve any matrix shape. Neither
    the number of inputs nor the number of outputs appears anywhere below.
    """
    row, rest = LSLICE(W, row_ref)
    return CAT(column(w_ref, row, x),
               crossbar(w_ref, row_ref, rest, x))


# ------------------------------------------------- the part that transfers

@morpho
def event_gate(feature, threshold, payload):
    """Run the expensive path only when a cheap feature says it is worth it.

    The paper's largest win is not the analog speed — it is that a cheap
    first estimate is fed to a detector, and the iterative stage is skipped
    entirely for uninteresting inputs. That is a decision, not a device, and
    it costs a comparator and a mask.

    Returns `payload` when feature >= threshold, zeros otherwise, so the
    downstream array sees no activity for signals that failed the test.
    """
    from tiny_morpho import Not, And, REPEAT
    diff, _borrow = brent_kung_adder(feature, Not(threshold), np.ones((1,), np.int32))
    fire = Not(diff[-1:])                       # no borrow => feature >= threshold
    return And(payload, REPEAT(fire, payload))


# ------------------------------------------------------------ verification

def refs(bits, n_in):
    return (np.zeros((bits, 1), np.int32),
            np.zeros((bits * n_in, 1), np.int32))


def check(n_out, n_in, bits=8, trials=32, seed=0):
    """Compare against the integer arithmetic the circuit is meant to do."""
    frac = bits // 2
    rng = np.random.default_rng(seed)
    lo, hi = -(1 << (bits - 1)), 1 << (bits - 1)
    mask = (1 << bits) - 1
    Wv = rng.integers(lo, hi, size=(n_out, n_in))
    xv = rng.integers(lo, hi, size=(trials, n_in))

    w_ref, row_ref = refs(bits, n_in)
    Wbus = np.concatenate([bits_of(np.repeat(Wv[o, i] & mask, trials), bits)
                           for o in range(n_out) for i in range(n_in)])
    xbus = np.concatenate([bits_of(xv[:, i] & mask, bits) for i in range(n_in)])
    out = crossbar(w_ref, row_ref, Wbus, xbus)

    def smul(a, b):
        return np.sign(a) * np.sign(b) * ((np.abs(a) * np.abs(b)) >> frac)

    for o in range(n_out):
        got = sref(ints_of(out[o * bits:(o + 1) * bits], bits), bits)
        want = sref(sum(smul(Wv[o, i], xv[:, i]) for i in range(n_in)) & mask, bits)
        assert np.array_equal(got, want), f"output {o} mismatch"
    print(f"  crossbar {n_out}×{n_in} @ W={bits}  bit-exact "
          f"({n_out * n_in} crosspoints, {trials} vectors)")


def cost(n_out, n_in, bits=8):
    w_ref, row_ref = refs(bits, n_in)
    c = compile(crossbar, [bits, bits * n_in, bits * n_in * n_out, bits * n_in])
    return len(c.ops), int(c.depths.max())


if __name__ == "__main__":
    print("morpho_crossbar — a matrix-vector product as a crossbar\n")
    print("correctness (signed Q4.4):")
    for n_out, n_in in ((1, 1), (2, 3), (3, 2), (4, 4)):
        check(n_out, n_in)

    print("\ncost — gates scale with area, depth only with the column:")
    print(f"  {'array':>10}  {'gates':>9}  {'depth':>6}  {'gates/crosspoint':>17}")
    for n_out, n_in in ((1, 1), (1, 4), (1, 16), (4, 4), (8, 8), (16, 16)):
        g, d = cost(n_out, n_in)
        print(f"  {n_out:>4}×{n_in:<5}  {g:>9,}  {d:>6}  {g / (n_out * n_in):>17.0f}")

    print("\nwhat this costs at model scale (d=384 projection, 147,456 crosspoints):")
    g1, _ = cost(1, 16)
    per = g1 / 16
    print(f"  fully parallel   {per * 147456 / 1e6:,.0f}M gates — not buildable")
    print( "  time-multiplexed one row of 384 crosspoints, reused 384 times:")
    print(f"                   {per * 384 / 1e3:,.0f}k gates, 384 cycles per output")

    print("\nagainst the analog article (Deng et al., Nat. Commun. 2026):")
    print("  analog   1 memristor per crosspoint. Crucially it does more than")
    print("           multiply: op-amp feedback makes the settling point solve")
    print("           A^T(AA^T)^-1 y — a pseudo-inverse in ~128 ns, no iteration.")
    print("           Paid for with 14-bit converters and a measured 1.83-5.61 dB")
    print("           loss to quantisation, wire resistance, parasitics and write error.")
    print(f"  digital  ~{per:.0f} gates per crosspoint, exact. The multiply maps over;")
    print("           the one-step inverse does not — digitally that is an iterative")
    print("           solve, and no arrangement of gates settles into an answer.")
    print("\nThe topology transfers. The physics does not — and their result is")
    print("mostly the physics.")
    print("\nWhat does transfer is their control flow. In the paper the cheap")
    print("operation runs once (MRI, ~6% of the time) and the expensive one")
    print("iterates (RSP, ~94%); the 45x energy win comes mostly from a detector")
    print("deciding which inputs deserve the expensive path at all. That is")
    print("ordinary logic — see event_gate below.")
