"""morpho_lm — a language model's recurrence, described in MorphoHDL.

Both RWKV-v4's wkv and Mamba's S6 reduce to one primitive:

    h  <-  a * h  +  b * u          with a = 2^(negative), so 0 < a <= 1

They differ only in where `a` comes from (a per-channel constant for RWKV, a
value computed from the input each token for Mamba) and in how wide the state
is (one scalar per channel for RWKV, an N-vector for Mamba). Neither
difference changes the cell — which is the point of describing it here rather
than in a framework: one recursive definition, both architectures, any width.

This file builds that cell out of the repository's own verified components
(`wallace_multiplier`, `brent_kung_adder`) and nothing else, and checks every
instantiation bit-exactly against a numpy reference.

    python morpho_lm.py            # run the verification suite

Fixed point: unsigned Qm.f throughout, i.e. an W-bit bus holding value
x / 2^f. Products are 2W bits wide and are sliced back to W — that slice is
pure wiring, no gates.
"""

import numpy as np

from tiny_morpho import (
    morpho, compile, LSLICE, CAT, ZERO, VOID,
    wallace_multiplier, brent_kung_adder,
)

# ---------------------------------------------------------------- helpers

def qmul(x, y, frac):
    """Fixed-point multiply: full product, then slice the Qf window back out.

    The slice is free in hardware — it selects which wires continue — so a
    Qm.f multiply costs exactly one Wallace tree and nothing more.
    """
    w = len(x)
    p = wallace_multiplier(x, y)          # 2W bits, Q(2m).(2f)
    return p[frac:frac + w]               # back to W bits, Q m.f


@morpho
def recur_step(h, a, b, u):
    """One state element, one tick:  h' = a*h + b*u.

    All four buses are the same width W and the same Q format. This is the
    entire architectural difference between RWKV and Mamba reduced to a cell:
    RWKV drives `a` from a constant register, Mamba drives it from a
    datapath. The cell cannot tell, and does not need to.
    """
    frac = len(h) // 2                    # Q(W/2).(W/2) by convention
    decayed = qmul(a, h, frac)
    driven = qmul(b, u, frac)
    total, _carry = brent_kung_adder(decayed, driven, ZERO)
    return total


def _bank_done(w, h, a, b, u):
    """Fallback: nothing left to peel, so the bank contributes nothing."""
    return VOID


@morpho(fallback=_bank_done)
def recur_bank(w, h, a, b, u):
    """A bank of independent state elements, generated by recursive division.

    `w` is a width reference — a bus one element wide — in the manner of the
    repository's own LSLICE/HSLICE/REPEAT. Each step peels one element off
    the front of every bus and recurses on the remainder; when nothing is
    left, LSLICE raises and the fallback ends the expansion.

    The bank size is therefore written down nowhere: pass one element or four
    thousand and the same definition expands to fit. That is the property
    that lets a single description serve RWKV's scalar-per-channel state and
    Mamba's N-wide state vector.
    """
    h0, hr = LSLICE(h, w)
    a0, ar = LSLICE(a, w)
    b0, br = LSLICE(b, w)
    u0, ur = LSLICE(u, w)
    return CAT(recur_step(h0, a0, b0, u0),
               recur_bank(w, hr, ar, br, ur))


# ------------------------------------------------------------ verification

def q(x, frac, bits):
    """float -> unsigned Qm.f integer, saturating."""
    v = np.round(np.asarray(x) * (1 << frac)).astype(np.int64)
    return np.clip(v, 0, (1 << bits) - 1)


def unq(v, frac):
    return np.asarray(v, dtype=np.float64) / (1 << frac)


def reference(h, a, b, u, frac, bits):
    """What the circuit should compute, in integer arithmetic."""
    lo = (a * h) >> frac
    hi = (b * u) >> frac
    return (lo + hi) & ((1 << bits) - 1)


def bits_of(vals, bits):
    """pack integers into a Morpho bus: shape (bits, n_lanes)."""
    vals = np.atleast_1d(np.asarray(vals, dtype=np.int64))
    return ((vals[None, :] >> np.arange(bits)[:, None]) & 1).astype(np.int32)


def ints_of(bus, bits):
    return (bus[:bits].astype(np.int64) << np.arange(bits)[:, None]).sum(0)


def check_cell(bits=8, trials=512, seed=0):
    """recur_step alone, against the integer reference."""
    frac = bits // 2
    rng = np.random.default_rng(seed)
    h, b, u = rng.integers(0, 1 << bits, size=(3, trials))
    a = rng.integers(0, 1 << frac, size=trials)      # decay <= 1.0
    got = ints_of(recur_step(bits_of(h, bits), bits_of(a, bits),
                             bits_of(b, bits), bits_of(u, bits)), bits)
    want = reference(h, a, b, u, frac, bits)
    assert np.array_equal(got, want), (
        f"mismatch at {bits} bits: first bad "
        f"{np.flatnonzero(got != want)[:3]}")
    print(f"  recur_step  W={bits:2d}  {trials} random cases  bit-exact")


def check_bank(bank_n, bits=8, trials=64, seed=1):
    """recur_bank at a width never written into the definition."""
    frac = bits // 2
    rng = np.random.default_rng(seed)
    shape = (trials, bank_n)
    h, b, u = rng.integers(0, 1 << bits, size=(3,) + shape)
    a = rng.integers(0, 1 << frac, size=shape)
    # lay the bank out along the bus: element k occupies bits [k*W, (k+1)*W)
    def bus(v):
        return np.concatenate([bits_of(v[:, k], bits) for k in range(bank_n)])
    out = recur_bank(np.zeros((bits, 1), np.int32),
                     bus(h), bus(a), bus(b), bus(u))
    for k in range(bank_n):
        got = ints_of(out[k * bits:(k + 1) * bits], bits)
        want = reference(h[:, k], a[:, k], b[:, k], u[:, k], frac, bits)
        assert np.array_equal(got, want), f"bank element {k} mismatch"
    print(f"  recur_bank  {bank_n:4d} elements × W={bits}  bit-exact "
          f"(definition never mentions {bank_n})")


def gate_count(bank_n, bits=8):
    """Compile to gates — the thing that would go to silicon."""
    w = bank_n * bits
    circuit = compile(recur_bank, [bits, w, w, w, w])
    return len(circuit.ops), int(circuit.depths.max())


# =====================================================================
#  Signed arithmetic, and the recurrence as an actual stateful circuit.
#
#  Above, the cell computes one step of h' = a*h + b*u in unsigned
#  fixed point. Two things are missing before that is a language model's
#  recurrence: the values are signed, and the state has to persist across
#  ticks. Both are addressed here using the sequential extension's REG.
# =====================================================================

from tiny_morpho import Not, Xor, REPEAT, ONE
from tiny_morpho_seq import REG, DRIVE, compile_seq


def cond_neg(x, s):
    """Two's-complement negate x when s is 1, leave it when s is 0.

    Negation is invert-then-increment, and both halves take s directly:
    XOR every bit with s, then feed s in as the carry. Costs one adder.
    """
    inv = Xor(x, REPEAT(s, x))
    out, _c = brent_kung_adder(inv, np.zeros((len(x),), np.int32), s)
    return out


def qmul_s(x, y, frac):
    """Signed fixed-point multiply, sign-magnitude.

    Take the magnitude of each operand, multiply unsigned (the verified
    Wallace tree), then negate the result if exactly one operand was
    negative. The sign is the MSB, so extracting it is wiring.
    """
    sx, sy = x[-1:], y[-1:]
    mag = qmul(cond_neg(x, sx), cond_neg(y, sy), frac)
    return cond_neg(mag, Xor(sx, sy))


@morpho
def recur_step_s(h, a, b, u):
    """Signed h' = a*h + b*u — the same cell, in two's complement."""
    frac = len(h) // 2
    total, _c = brent_kung_adder(qmul_s(a, h, frac), qmul_s(b, u, frac), ZERO)
    return total


def make_channel(width, decay_is_constant, decay_init=None):
    """Build ONE recurrent channel, holding its own state in a register.

    decay_is_constant=True   -> RWKV: `a` is a per-channel constant baked
                                into the circuit, so no wires carry it
    decay_is_constant=False  -> Mamba: `a` arrives on a bus, recomputed by
                                the datapath every tick

    Both return the same cell around the same register. The architectural
    difference is entirely in where `a` comes from.
    """
    if decay_is_constant:
        const = np.asarray(decay_init, dtype=np.int32)

        @morpho
        def channel(b, u):
            h = REG(np.zeros(width, np.int32))
            nxt = recur_step_s(h, const, b, u)
            DRIVE(h, nxt)
            return h
        return channel

    @morpho
    def channel(a, b, u):
        h = REG(np.zeros(width, np.int32))
        nxt = recur_step_s(h, a, b, u)
        DRIVE(h, nxt)
        return h
    return channel


# ------------------------------------------------------------ verification

def sref(v, bits):
    """interpret an unsigned bit pattern as two's complement."""
    v = np.asarray(v, dtype=np.int64)
    return np.where(v >> (bits - 1), v - (1 << bits), v)


def recur_reference(a, b, u, bits, frac, steps):
    """Integer reference for the stateful recurrence, matching the circuit:
    sign-magnitude multiply (truncation toward zero), wrapping add."""
    mask = (1 << bits) - 1
    def smul(x, y):
        s = np.sign(x) * np.sign(y)
        return s * ((abs(x) * abs(y)) >> frac)
    h = np.zeros(b.shape[1:], dtype=np.int64)
    out = []
    for t in range(steps):
        h = smul(a[t], h) + smul(b[t], u[t])
        h = sref(h & mask, bits)
        out.append(h.copy())
    return np.array(out)


def check_signed_cell(bits=8, trials=512, seed=3):
    """recur_step_s, against the signed integer reference."""
    frac = bits // 2
    rng = np.random.default_rng(seed)
    h, b, u = rng.integers(-(1 << (bits - 1)), 1 << (bits - 1), size=(3, trials))
    a = rng.integers(0, 1 << frac, size=trials)          # decay in [0,1)
    mask = (1 << bits) - 1
    got = sref(ints_of(recur_step_s(bits_of(h & mask, bits), bits_of(a, bits),
                                    bits_of(b & mask, bits),
                                    bits_of(u & mask, bits)), bits), bits)
    def smul(x, y):
        return np.sign(x) * np.sign(y) * ((abs(x) * abs(y)) >> frac)
    want = sref((smul(a, h) + smul(b, u)) & mask, bits)
    bad = np.flatnonzero(got != want)
    assert len(bad) == 0, f"{len(bad)}/{trials} mismatched, e.g. index {bad[:3]}"
    print(f"  recur_step_s  W={bits:2d}  {trials} signed cases  bit-exact")


def check_stateful(bits=8, steps=24, samples=8, seed=5, constant_decay=True):
    """The register loop, run for many ticks, against the reference."""
    frac = bits // 2
    rng = np.random.default_rng(seed)
    mask = (1 << bits) - 1
    b = rng.integers(-(1 << (bits - 1)), 1 << (bits - 1), size=(steps, samples))
    u = rng.integers(-(1 << (bits - 1)), 1 << (bits - 1), size=(steps, samples))
    a_const = int(rng.integers(1, 1 << frac))

    def buses(vals):                       # (steps, samples) -> (bits, steps, samples)
        return ((vals[None] & mask) >> np.arange(bits)[:, None, None]) & 1

    if constant_decay:
        cell = make_channel(bits, True, bits_of(a_const, bits)[:, 0])
        sim = compile_seq(cell, (bits, bits))
        trace = sim.run(steps, buses(b), buses(u))
        a_arr = np.full(steps, a_const)
    else:
        a = rng.integers(0, 1 << frac, size=(steps, samples))
        cell = make_channel(bits, False)
        sim = compile_seq(cell, (bits, bits, bits))
        trace = sim.run(steps, buses(a), buses(b), buses(u))
        a_arr = a

    got = sref((trace.astype(np.int64) <<
                np.arange(bits)[:, None, None]).sum(0), bits)
    want = recur_reference(a_arr, b, u, bits, frac, steps)
    # sim.run returns the register value observed each tick; align on the
    # states the reference produces after each update
    assert got.shape == want.shape, f"{got.shape} vs {want.shape}"
    lag = 1 if not np.array_equal(got, want) and np.array_equal(got[1:], want[:-1]) else 0
    ok = np.array_equal(got[lag:], want[:len(want) - lag])
    assert ok, ("stateful mismatch; first differing tick "
                f"{np.flatnonzero((got[lag:] != want[:len(want)-lag]).any(1))[:1]}")
    kind = "constant decay (RWKV)" if constant_decay else "decay per tick (Mamba)"
    print(f"  {kind:24s} {steps} ticks × {samples} lanes  bit-exact"
          + (f"  [register reads one tick behind]" if lag else ""))


if __name__ == "__main__":
    print("morpho_lm — the shared recurrence of RWKV and Mamba, in MorphoHDL\n")
    print("cell:")
    for bits in (4, 8, 12, 16):
        check_cell(bits=bits)
    print("\nbank — one definition, widths it was never told about:")
    for n in (1, 2, 3, 5, 8, 16):
        check_bank(n, bits=8)
    print("\ncompiled to gates (Q4.4 elements) — linear in bank size, "
          "constant in depth:")
    for n in (1, 2, 4, 8, 16):
        g, d = gate_count(n, 8)
        print(f"  {n:3d} elements  {g:7d} gates   logic depth {d}")
    print("\nsigned (two's complement):")
    for bits in (8, 12, 16):
        check_signed_cell(bits=bits)

    print("\nstateful — the recurrence closed through a register:")
    check_stateful(constant_decay=True)
    check_stateful(constant_decay=False)

    print("\ngates for one stateful channel (Q4.4, signed):")
    for name, const in (("RWKV  (decay baked in)", True),
                        ("Mamba (decay on a bus)", False)):
        cell = make_channel(8, const, bits_of(9, 8)[:, 0] if const else None)
        sim = compile_seq(cell, (8, 8) if const else (8, 8, 8))
        print(f"  {name}  {len(sim.c.ops):5d} gates")

    print("\nRWKV drives `a` from a constant; Mamba computes it per token.")
    print("The cell is identical. That is the observation this file exists to make.")